" Daniels vimrc
" -----------------------------------------------------------------------------


" pathogen is nice to handle plugins!
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
execute pathogen#helptags()


syntax on
filetype plugin indent on
set number


" colors help a lot
if $TERM == "linux"
	" i tried to use solarized colors in linux console ... but failed.
	colorscheme default
else
	" else it breaks in xterm
	let g:solarized_termcolors=256
	colorscheme solarized
endif
" more relaxing for the eyes
set background=light

