" Daniels vimrc
" -----------------------------------------------------------------------------


" pathogen is nice to handle plugins!
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
execute pathogen#helptags()


syntax on
filetype plugin indent on
set number


set list
"set listchars=tab:»-,trail:·,eol:¶
set listchars=tab:»-,trail:·,extends:‹,precedes:›
set showbreak=›-»
set colorcolumn=80

set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=4

" colors help a lot
if $TERM == "linux"
	" i tried to use solarized colors in linux console ... but failed.
	colorscheme default
else
	" else it breaks in xterm
	let g:solarized_termcolors=256
	colorscheme solarized
endif
" more relaxing for the eyes
set background=light


iab //L // ----------------------------------------------------------------------------

