runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
execute pathogen#helptags()
syntax on
filetype plugin indent on



set background=light
let g:solarized_termtrans=1
if $TERM == "linux"
	let g:solarized_termcolors = 16
else
	let g:solarized_termcolors = 256
endif
colorscheme solarized

