#!/bin/sh
#
# ~/.xinitrc
#

# source system xinitrc files ... this will be removed TODO
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# disable touchpad tapping
synclient TapButton1=0
synclient TapButton2=0
synclient TapButton3=0

# Add /usr/share/fonts/local to the fontpath
xset +fp /usr/share/fonts/local
xset fp rehash

# Load Xresources
xrdb -load ~/.Xresources
# Load solarized colors
xrdb -merge ~/dotfiles/x/solarized-xresources/solarized


exec /usr/bin/i3

