#!/bin/sh


# system files
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Add /usr/share/fonts/local to the fontpath
xset +fp /usr/share/fonts/local
xset fp rehash

# Load Xresources
xrdb -load ~/dotfiles/x/resources
# Load solarized colors
xrdb -merge ~/dotfiles/x/solarized-xresources/solarized

exec herbstluftwm
