#!/bin/sh


# system files
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

touch ~/OK

# Load Xresources
xrdb -load ~/dotfiles/x/resources
# Load solarized colors
xrdb -merge ~/dotfiles/x/solarized-xresources/solarized
# Load dzen2 (panel) settings
xrdb -merge ~/dotfiles/x/dzen2.resources

setxkbmap de

exec herbstluftwm
